#!/bin/bash

# Usage: sch_export [-d] OUTPUT_PDF SCHEMATIC_FILES ...
# Desc: Generates multipage pdf from schematic files
#       Page order defined by 'page' attributes in the schematics
#       -d set 'date' attribute of the schematics to the current date

set -e

PDFS=""
DATE=""
if [ "$1" = "-d" ]; then
  DATE=`date +%Y-%m-%d`
  shift
fi
OUT="$1"
shift

for f in "$@"
do
  if [ -n "$DATE" ]; then
    sed -i "s/date=.*/date=$DATE/" $f
  fi
  num=`grep -oP '(?<=page=)\d+' $f`
  num=`echo $(printf '%03d' $num)`
  gaf export -o "${num}_${f%.sch}.pdf" $f
  PDFS="$PDFS ${num}_${f%.sch}.pdf"
done

PDFS=`echo $PDFS | xargs -n1 | sort -u | xargs`

pdfunite $PDFS $OUT

rm $PDFS
